# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Md365 < Formula
  desc "AI- and human-friendly CLI for Microsoft 365 - calendars, contacts, and mail as Markdown"
  homepage "https://github.com/lcorneliussen/md365"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lcorneliussen/md365/releases/download/v0.3.0/md365_0.3.0_darwin_amd64.tar.gz"
      sha256 "0b12a6505c1c7ff54c7c31f25fd226f870fb8cfb9bba52a19eea8d5260e799c0"

      define_method(:install) do
        bin.install "md365"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lcorneliussen/md365/releases/download/v0.3.0/md365_0.3.0_darwin_arm64.tar.gz"
      sha256 "ae50ab33f1c2ad5557779ea35e0685bf0dc39ed2c83a496e2293ee42a199bd41"

      define_method(:install) do
        bin.install "md365"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lcorneliussen/md365/releases/download/v0.3.0/md365_0.3.0_linux_amd64.tar.gz"
      sha256 "b9449885f5d47030e5642da1649ba2367b27eca3335ebf5ee1e61e325fa95640"
      define_method(:install) do
        bin.install "md365"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lcorneliussen/md365/releases/download/v0.3.0/md365_0.3.0_linux_arm64.tar.gz"
      sha256 "809534125da23e7dbb8ca6a6db10dadac44dcd6cab1354e6884df90bd2a9f914"
      define_method(:install) do
        bin.install "md365"
      end
    end
  end

  test do
    system "#{bin}/md365", "--help"
  end
end
