# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Md365 < Formula
  desc "AI- and human-friendly CLI for Microsoft 365 - calendars, contacts, and mail as Markdown"
  homepage "https://github.com/lcorneliussen/md365"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lcorneliussen/md365/releases/download/v0.2.2/md365_0.2.2_darwin_amd64.tar.gz"
      sha256 "7f034fb587d50b731447c1af8d572938b97a5ab97c550e1b495b7409cf9df754"

      define_method(:install) do
        bin.install "md365"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lcorneliussen/md365/releases/download/v0.2.2/md365_0.2.2_darwin_arm64.tar.gz"
      sha256 "452a769e03ea08534ab253ae0d35ca5b49784244236f98e6081b9bfa12fd3458"

      define_method(:install) do
        bin.install "md365"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lcorneliussen/md365/releases/download/v0.2.2/md365_0.2.2_linux_amd64.tar.gz"
      sha256 "20da7d198d19c8740c8ca73b2ed3da0b048dab89ef82f9d74ec67bb12fedfbb0"
      define_method(:install) do
        bin.install "md365"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lcorneliussen/md365/releases/download/v0.2.2/md365_0.2.2_linux_arm64.tar.gz"
      sha256 "1216b037d20cd32d3c3970c308acc78e9cdbf359d79ff5876272cbf0e0c1e9a0"
      define_method(:install) do
        bin.install "md365"
      end
    end
  end

  test do
    system "#{bin}/md365", "--help"
  end
end
